### ISSUE TITLE
Crashing on launch. 

### ISSUE THREAD

**Issue by MaDmaxwell311** [draknyte1/MiscUtilities#8] opened 2016-08-27 00:04 UTC
I was shown this mod earlier today and I wanted to try it out, sadly upon launch, this happens. http://pastebin.com/s2Yd5tzV

**Comment by MaDmaxwell311** [comment] 2016-08-27 01:07
Update: Tried with Version: 1.4.3.13.1 
New crashlog: http://pastebin.com/ABBe3vkT

**Comment by draknyte1** [comment] 2016-08-27 04:56
It's related to the latest change in GT 5.9, regarding how new materials are added and stored.
I've been away for a week up until yesterday and adding compatibility for this change isn't really on my top to-do with RL taking up my next week rather fully.

Let me see what I can do, no promises it will be today/tomorrow though sorry.

**Comment by MaDmaxwell311** [comment] 2016-08-27 05:06
That is all good, I will be paying attention for your new releases and test them for you.

**Comment by draknyte1** [comment] 2016-08-27 05:08
https://github.com/Blood-Asp/GT5-Unofficial/issues/507

Actually, the issue is your version is too old.
I am using the already correct spelling ;)

What version of GT are you using?

**Comment by draknyte1** [comment] 2016-08-27 05:10
Caused by: java.lang.NoSuchFieldError: PRAECANTATIO
Caused by: java.lang.NoSuchFieldError: COGNITIO

^ Only reason I say that is the ones missing are the ones spelt wrong and the TC stuff wasn't changed like I thought after having a proper look.

**Comment by draknyte1** [comment] 2016-08-27 06:51
Close this if you consider it fixed mate.

**Closed** 2016-08-27 18:05 UTC

**Comment by leagris** [comment] 2016-08-29 16:22
Some other related crash:
https://pastebin.com/narLgE6p
